### ISSUE TITLE
Investigate array jobs

### ISSUE THREAD

**Issue by gdevenyi** [CobraLab/antsRegistration-MAGeT#2]
Scinet doesn't like having too many dependencies, do array jobs solve this? I want the jobs to be as independent as possible.

**Comment by pipitone** [comment]
They surely do solve this. Take a look at my hacky script for this here: 
https://github.com/TIGRLab/quarantine/blob/master/SGE-extras/1.0/src/bin/sge_submit_array

or this thing I just found: 
https://github.com/qarray/qarray

I think with a small amount of engineering effort we could make a nicer `qbatch` that does local (#3), array, or individual jobs.

**Comment by gdevenyi** [comment]
How does that sge_submit_array work? A quick reading I can't really tell how that array magicks work.

**Comment by pipitone** [comment]
An array job is just a script that is run multiple times, each time the environment variable `SGE_TASK_ID` takes on a new number from whatever range you specify with `qsub -t1..n`. 

The `sge_submit_array` command takes a file with a list of commands, and creates a script that when called as an array job, runs the `SGE_TASK_ID`th line of the command list file. Line 22 is where the magic happens: a sed command grabs the line from the file and the enclosing `$( )` runs it.

**Comment by pipitone** [comment]
I'm cooking up a slightly less hacky version of `sge_submit_array` over here: 
https://github.com/pipitone/qbatch

PRs or comments welcome.

**Comment by gdevenyi** [comment]
Coming soon: stolen qbatch with array jobs.
