### ISSUE TITLE
Generic QC images?

### ISSUE THREAD

**Issue by gdevenyi** [CobraLab/antsRegistration-MAGeT#23]
Can we auto-generate some generic QC images?

Uncle Ed requests them.

Problems:
- Can ANTs do anything useful in this?
- Job dependencies of running at the end of the entire pipeline.

**Comment by egarza** [comment]
It could be a script that you can use after all is run, such as "mb qc".

**Comment by gdevenyi** [comment]
That's the plan.

**Comment by gdevenyi** [comment]
@egarza possible implementation here https://github.com/CobraLab/minc-toolkit-extras/blob/master/MaGeT-QC.sh please test and report back

**Comment by gdevenyi** [comment]
Implemented and seems to work
