### ISSUE TITLE
"Error:  Unrecognized interpolation option. genericlabel" in mb_resample.sh

### ISSUE THREAD

**Issue by pipitone** [CobraLab/antsRegistration-MAGeT#48]
When running the resample stage, I get the following errors:
```
mb_resample.sh label_hc.mnc input/atlas/subject3_t1.mnc input/template/subject3_t1.mnc input/subject/subject1_t1.mnc
Error:  Unrecognized interpolation option. genericlabel
```

I'm using minc-toolkit 1.9.11 on centos 6.7... is this an ANTS version thing?

**Comment by gdevenyi** [comment]
Probably, here's the commit https://github.com/stnava/ANTs/commit/3013473ae7bf849212bc13d98ca99e78e057a161

I've been testing this mostly on stnava/ANTs because I want to reduce the dependency footprint.

You could switch to MultiLabel in the meantime

**Comment by pipitone** [comment]
FYI I had to switch to `NearestNeighbor` interpolation.. `MultiLabel` was giving me empty labels for whatever reason.

**Comment by gdevenyi** [comment]
Have you tested with MultiLabel on a stock version of ANTs? If that fails, they should know about it...

**Comment by pipitone** [comment]
Nope, I have only tested with minc-toolkit 1.9.11.

**Comment by pipitone** [comment]
Is there a particular version of ANTs you recommend?

**Comment by gdevenyi** [comment]
Sadly, there aren't any "versions" 2.1.0 is super-old. Pretty much the only option is building from git HEAD.

**Comment by pipitone** [comment]
Hmm.. Okay that sucks.  I'll file an issue ;-)

**Comment by gdevenyi** [comment]
Resolved by readme update.
