### ISSUE TITLE
job name

### ISSUE THREAD

**Issue by dcoynel** [CobraLab/antsRegistration-MAGeT#69]
The naming of the jobs is problematic on a SGE system: it does not accept object names starting with a digit, or including special characters. 

This appears to be fixed by replacing L23 of mb.sh from:
`datetime=$(date -u +%F-%R:%S)`

to (for example):
`datetime=N$(date -u +%F_%H-%M-%S)`

**Comment by gdevenyi** [comment]
Fixed by fac39a861ce200ce329bcee60e53600420e63628

Thanks.
