### ISSUE TITLE
Python issue on systems with 2 and 3

### ISSUE THREAD

**Issue by cfhammill** [CobraLab/antsRegistration-MAGeT#96]
This is probably just an issue with our setup, but antsRegistration-MAGeT calls `python` which on most systems will use python2, on systems configured to use python3 (i.e. PYTHONPATH set to 3 libs) python2 can crash when it tries to load libraries.

**Comment by gdevenyi** [comment]
You're right, sounds like a local python config issue.

I hate the mess that is python library paths.

I've been investigating using virtualenvs for everything...
